version: '2'

services:
  redis:
    image: redis
    container_name: sentry_redis
ٰ    networks: 
      - default

  postgres:
    image: postgres
    container_name: sentry_postgres
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: 
    volumes:
     - ./pgdb:/var/lib/postgresql/data
ٰ    networks: 
      - default
  sentry:
    image: sentry
    container_name: sentry
    links:
     - redis
     - postgres
    volumes:
     - ./conf:/etc/sentry
    ports:
      - 9000:9000
    environment:
      SENTRY_SECRET_KEY:
      SENTRY_POSTGRES_HOST:
      SENTRY_DB_USER: 
      SENTRY_DB_PASSWORD:
      SENTRY_REDIS_HOST:
    networks: 
      - default

  cron:
    image: sentry
    container_name: sentry_cron
    links:
     - redis
     - postgres
    volumes:
     - ./conf:/etc/sentry
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: 
      SENTRY_POSTGRES_HOST:
      SENTRY_DB_USER: 
      SENTRY_DB_PASSWORD:
      SENTRY_REDIS_HOST: 
    networks: 
      - default      

  worker:
    image: sentry
    container_name: sentry_worker
    links:
     - redis
     - postgres
    command: "sentry run worker"
    volumes:
     - ./conf:/etc/sentry
    environment:
      SENTRY_SECRET_KEY: 
      SENTRY_POSTGRES_HOST:
      SENTRY_DB_USER: 
      SENTRY_DB_PASSWORD: 
      SENTRY_REDIS_HOST: 
ٰ    networks: 
      - default
networks:
  default:
